### ISSUE TITLE
GitHub requires open access publication

### ISSUE THREAD

**Issue by GeorgLink** [OSSHealth/HealthIndicators#11]
You might have seen that GitHub is [proposing new Terms of Service](https://github.com/blog/2314-new-github-terms-of-service).

Interestingly, GitHub would like to [require academic publications to be open access](https://help.github.com/articles/github-terms-of-service-draft/#5-scraping):
> Researchers may scrape public, non-personal information from GitHub for academic research purposes, only if any publications resulting from that research are open access.

I don't know whether our publications will be open access. 
Maybe, having the software here on GitHub under MIT license meets the requirement that "any publication"?

**Comment by germonprez** [comment]
Same issue within 6 minutes of each other! Impressive :)

Our publications are aiming to be open access anyway. I believe this was part of the requirements from Sloan. I think that the only publication that we would produce by using our own tool is when we point it across the entire GH landscape to determine community types. But this paper is a long way away at the moment.

**Comment by GeorgLink** [comment]
The issue appears to be resolved.
